### ISSUE TITLE
pre hook and post hook can not work together on a same request?

### ISSUE THREAD

**Issue by WIZARD-CXY** [ClusterHQ/powerstrip#68]
Hi,I was using go-dockerclient and powerstrip these days.I was using a adapter.yml file as shown below.There are preHook and postHook defined on the same `POST /containers/*/start`.But from the adapter's log I only saw the postHook was called, the preHook is never called, I was curious why?Thanks in advance!
```
version: 1
endpoints:
  "POST /containers/*/start":
    pre: [socketplane]
  "POST /containers/*/start":
    post: [socketplane]
  "DELETE /*/containers/*":
    post: [socketplane]
adapters:
  socketplane: http://localhost:6675/adapter

```

**Comment by exarkun** [comment]
Hi!

Thanks for your interest in powerstrip.  Looking at your configuration file, my guess is that the problem is caused by the pre- and post-hooks being specified in different items in the `endpoints` section:

```
  "POST /containers/*/start":
    pre: [socketplane]
  "POST /containers/*/start":
    post: [socketplane]
```

Instead of this, try:

```
  "POST /containers/*/start":
    pre: [socketplane]
    post: [socketplane]
```

I think that what happens when the configuration file is written the way it is in the issue description is that the post-hook configuration completely replaces the pre-hook configuration.

Perhaps it would be better if configuration with this mistake were reported as an error instead of just silently behaving differently than you expect. What do you think, @binocarlos ?

**Comment by WIZARD-CXY** [comment]
works like a charm!  I think it would be the best to specify such details in the doc for the user
Thanks !

**Comment by robhaswell** [comment]
@exarkun that would be ideal, but it is the underlying YAML parser which munches this information. The YAML spec says that the parser should display a warning. It also seems that PyYAML behaves incorrectly here with respect to which key value is preserved. This issue was reported 6 years ago: http://pyyaml.org/ticket/128.
